version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    environment:
      RAILS_ENV: production
    entrypoint: bin/entry
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/braveproject
    ports:
      - "3000:3000"
    depends_on:
      - db